### ISSUE TITLE
NumPy data type issue

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA#159]
A user reported a problem with SoFiA crashing while running the S+C finder with the following error message:

    Traceback (most recent call last):
      File "/SoFiA-master/sofia_pipeline.py", line 366, in <module>
        pyfind.SCfinder_mem(np_Cube, mask, dict_Header, t0, **Parameters["SCfind"])
      File "/SoFiA-master/build/lib.linux-x86_64-2.7/sofia/pyfind.py", line 73, in SCfinder_mem
        mask |= (np.absolute(cube_smooth) >= threshold * rms_smooth)
    TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
    Pipeline failed with exit code 1.

The problem occurs when feeding a mask cube into SoFiA and the S+C finder is trying to add detected pixels to that mask using NumPy’s `bitwise_or` operator or function. The problem has occurred in past and was thought to have been resolved, but apparently is still causing problems in some situations. It originally resulted from changes in the way different data types are being coerced in NumPy version&nbsp;1.10 and higher.

I vaguely remember that we resolved the problem by changing the data type of the mask array from Boolean to integer, but we may need to go one step further and force NumPy to automatically cast different data types by adding the `casting='unsafe'` option to the `bitwise_or()` function call, which was the default behaviour prior to NumPy&nbsp;1.10.

**Comment by paoloserra** [comment]
Could you add the full log? I'd like to know what version of Python, Numpy etc were being used.

**Comment by SoFiA-Admin** [comment]
Unfortunately, this is all I have, although the same user reported another issue that turned out to be due to conflicting Python versions, so I have reason to assume that the final, successful installation was using Python 2.7 (instead of 3.7.3, which was also installed). I cannot reproduce the error either, but remember that we had this problem as well in the past due to a change that occurred in NumPy a while ago. Using `casting='unsafe'` in all NumPy arithmetic on arrays should make the error disappear, but I don’t know what the side effects would be in the case of incompatible types.

**Comment by paoloserra** [comment]
I've been able to reproduce this error. It seems that the input mask is imported as float32, which is not compatible with bool. If the input mask is converted to int32 the problem disappears. For example, this can be done adding `mask=mask.astype('int32')` before the line

https://github.com/SoFiA-Admin/SoFiA/blob/3c4f277bd14d7e18ea4a7b14f3c5c2e594464717/sofia/import_data.py#L462

This would be consistent with the data type we have chosen for the initial empty mask when no input mask is given, as can be seen at 

https://github.com/SoFiA-Admin/SoFiA/blob/3c4f277bd14d7e18ea4a7b14f3c5c2e594464717/sofia/import_data.py#L481-L482

Since I'm not sure whether there were good reasons to import the input mask as float32, I will wait for comments before committing this change.

**Comment by paoloserra** [comment]
Here's a few lines of Python2 showing that a mask created by SoFiA is imported as float32 by **my** astropy.fits. Note that BITPIX = 16 and there's no BZERO, BSCALE.

```
>>> from astropy.io import fits
>>> file='/home/pserra/Astro/helmut/NEWmosaics/sofia66/SWmosaic.dkb12.15.16.line.felo.imap.pb_mask.fits'
>>> f=fits.open(file)
>>> f[0].data.dtype
dtype('float32')
>>> f[0].header
SIMPLE  =                    T / conforms to FITS standard                      
BITPIX  =                   16 / array data type                                
NAXIS   =                    4 / number of array dimensions                     
NAXIS1  =                  199                                                  
NAXIS2  =                  203                                                  
NAXIS3  =                  340                                                  
NAXIS4  =                    1                                                  
BLANK   =                   -1  /                                               
BUNIT   = 'source_ID'                                                           
DATE-OBS= '2015-09-05T23:16:03.4'  /                                            
TELESCOP= 'ATCA    '  /                                                         
CRPIX1  =    1.09000000000E+02  /                                               
CDELT1  =   -4.16666682546E-04  /                                               
CRVAL1  =    1.75239833315E+02  /                                               
CTYPE1  = 'RA---CAR'  /                                                         
CRPIX2  =    6.50000000000E+01  /                                               
CDELT2  =    4.16666682546E-04  /                                               
CRVAL2  =   -2.64933333050E+01  /                                               
CTYPE2  = 'DEC--CAR'  /                                                         
CRPIX3  =    1.00000000000E+00  /                                               
CDELT3  =    4.19354807339E+04  /                                               
CRVAL3  =   -7.16735403751E+06  /                                               
CTYPE3  = 'VELO-HEL'  /                                                         
CRPIX4  =    1.00000000000E+00  /                                               
CDELT4  =    1.00000000000E+00  /                                               
CRVAL4  =    1.00000000000E+00  /                                               
CTYPE4  = 'STOKES  '  /                                                         
CELLSCAL= '1/F     '  /                                                         
RESTFREQ=    3.64641799927E+10  /                                               
SPECSYS = 'BARYCENT'  /                                                         
VOBS    =   -9.72624123096E-01  /                                               
BTYPE   = 'intensity'  /                                                        
EPOCH   =    2.00000000000E+03  /                                               
LTYPE   = 'velocity'  /                                                         
LSTART  =   -7.16735400391E+03  /                                               
LSTEP   =    4.19354820251E+01  /                                               
LWIDTH  =    4.19354820251E+01  /                                               
OBJECT  = 'dkb12   '  /                                                         
OBSERVER= 'Dannerbauer'  /                                                      
PBTYPE  = 'SINGLE  '  /                                                         
ORIGIN  = 'SoFiA 1.3.1'                                                         
DATAMIN =                    0                                                  
DATAMAX =                    5                                                  

```

**Comment by vdhulst** [comment]
tried this in Python3 with mixed results:

file1:
```
>>> file='../u624_3.5rms_rel0.95_dilation_mask.fits'
>>> f=fits.open(file)
>>> f[0].data.dtype
dtype('>i2')
>>> f[0].header
SIMPLE  =                    T / conforms to FITS standard                      
BITPIX  =                   16 / array data type                                
NAXIS   =                    3 / number of array dimensions                     
NAXIS1  =                  512                                                  
NAXIS2  =                  512                                                  
NAXIS3  =                   89                                                  
BLOCKED =                    T / TAPE MAY BE BLOCKED                            
CDELT1  =  -1.388670000000E-03 / PRIMARY PIXEL SEPARATION                       
CRPIX1  =   2.570000000000E+02 / PRIMARY REFERENCE PIXEL                        
CRVAL1  =   1.446819000000E+01 / PRIMARY REFERENCE VALUE                        
CTYPE1  = 'RA---NCP          ' / PRIMARY AXIS NAME                              
CUNIT1  = 'DEGREE            ' / PRIMARY AXIS UNITS                             
CDELT2  =   1.388670000000E-03 / PRIMARY PIXEL SEPARATION                       
CRPIX2  =   2.570000000000E+02 / PRIMARY REFERENCE PIXEL                        
CRVAL2  =   3.039918000000E+01 / PRIMARY REFERENCE VALUE                        
CTYPE2  = 'DEC--NCP          ' / PRIMARY AXIS NAME                              
CUNIT2  = 'DEGREE            ' / PRIMARY AXIS UNITS                             
CDELT3  =  -3.906250000000E+04 / PRIMARY PIXEL SEPARATION                       
CRPIX3  =   5.100000000000E+01 / PRIMARY REFERENCE PIXEL                        
CRVAL3  =   1.398249276359E+09 / PRIMARY REFERENCE VALUE                        
CTYPE3  = 'FREQ-OHEL         ' / PRIMARY AXIS NAME                              
CUNIT3  = 'HZ                ' / PRIMARY AXIS UNITS                             
DRVAL3  =   4.778000000000E+03 / SECONDARY REFERENCE VALUE                      
DTYPE3  = 'VELO              ' / SECONDARY AXIS NAME                            
DUNIT3  = 'KM/S              ' / SECONDARY AXIS UNITS                           
EPOCH   =   1.950000000000E+03 / EPOCH                                          
FREQ0   =   1.420405752000E+09 / REST FREQUENCY                                 
INSTRUME= 'WSRT              ' / INSTRUMENT                                     
DATAMAX =                    3 / MAXIMUM DATA VALUE                             
DATAMIN =                    0 / MINIMUM DATA VALUE                             
ORIGIN  = 'SoFiA 1.2.1-beta'   / VERSION OF THE GIPSY PROGRAM                   
OBJECT  = 'UGC624      '                                                        
BMMAJ   = 0.24225079808841D+02                                                  
BMMIN   = 0.10695456889255D+02                                                  
SUBTR   =                    0 /SOURCE SUBTRACTION                              
CHANEND =                   51 / last usable continuum channel                  
UVCDT   = 'NORMAL     '        /UV COORDINATE TYPE                              
BLGRAD  = 'GAUSSIAN   '        /TAPER TYPE                                      
FFTRA   =                 1024 /FFT SIZE IN R.A.                                
MAPTYP  = 'MAP'                                                                 
INSECT  =                    1 /INPUT SECTORS.                                  
BUNIT   = 'source_ID'                                                           
FIRSTLCH=                  -38 / low velocity edge of line signal               
DATE    = '10/10/01'                                                            
CHANSTA =                  -59 / 1st usable continuum channel                   
PCDEC   =             30.39918 /POINTING CENTRE DEC (DEG)                       
FREQR   =       1398249276.359 /REFERENCE FREQUENCY (HERTZ)                     
LASTLCH =                   35 / high velocity edge of line signal              
DATTYP  = 'NORMAL     '        /DATA TYPE                                       
BMPA    = 0.00000000000000D+00                                                  
DATE-OBS=             2000.545                                                  
CLIP    =                    0 /CLIPPING DONE                                   
FFTDEC  =                 1024 /FFT SIZE IN DEC.                                
PGCNR   =                99999                                                  
NFREQ   =                  127 /TOTAL # OF FREQUENCY POINTS                     
INPTS   =                60384 /INPUT POINTS.                                   
CRESL3  =             39062.50 /BANDWIDTH (HERTZ)                               
PCRA    =             14.46819 /POINTING CENTRE R.A. (DEG)                      
NINTF   =                   91 /TOTAL INTERFEROMETERS                           
TAPENUM =                    0 / tapenumber containing raw and reduced data     
CORGRID =                    1 /CORRECT FOR CONVOLUTION                         
UVGRID  = 'EXP*SINC   '        /CONVOLUTION TYPE                                
NOISE   = 0.11934600000000D+00 / updated averaged noise in maps                 
POL     = 'L'                                                                   
BANDW   =              4960938 /TOTAL BANDWIDTH OF OBS(HERTZ)                   
VEL     =              4242894 /CENTRE VELOCITY (M/S)                           
NORM    =             32215.01 /NORM. FACTOR IN FFT                             
DEBEAM  =                    0 /DE-BEAM COUNT                                   
VELR    =              4778000 /REFERENCE VELOCITY (M/S)                        
SETNR   =                    1 /# OF SET.                                       
MAPLAB  =                    0 /LABEL OF THIS MAP                               
COMMENT   FULL RESOLUTION MAPS (127) OF U624                                    
COMMENT continuum subtracted                                                    
COMMENT cleaned to 0.5*sigma and restored                                       
```
file 2:
```
>>> file='test_mask.fits'
>>> f=fits.open(file)
>>> f[0].data.dtype
dtype('float32')
>>> f[0].header
SIMPLE  =                    T / conforms to FITS standard                      
BITPIX  =                   16 / array data type                                
NAXIS   =                    3 / number of array dimensions                     
NAXIS1  =                 3000                                                  
NAXIS2  =                 3000                                                  
NAXIS3  =                    1                                                  
BLANK   =                   -1  /                                               
BUNIT   = 'source_ID'                                                           
DATE-OBS= '2010-05-03T16:49:20.2'  /                                            
TELESCOP= 'WSRT    '  /                                                         
CRPIX1  =    1.50100000000E+03  /                                               
CDELT1  =   -5.55555576728E-04  /                                               
CRVAL1  =    1.84739750011E+02  /                                               
CTYPE1  = 'RA---SIN'  /                                                         
CRPIX2  =    1.50100000000E+03  /                                               
CDELT2  =    5.55555576728E-04  /                                               
CRVAL2  =    4.73039720062E+01  /                                               
CTYPE2  = 'DEC--SIN'  /                                                         
CELLSCAL= 'CONSTANT'  /                                                         
RESTFREQ=    1.40852477916E+09  /                                               
SPECSYS = 'TOPOCENT'  /                                                         
BMAJ    =    4.56397421658E-03  /                                               
BMIN    =    3.22419847362E-03  /                                               
BPA     =   -2.52061843872E+00  /                                               
OBSERVER= 'ProcessD'  /                                                         
OBJECT  = 'ngc4258 '  /                                                         
EPOCH   =    2.00000000000E+03  /                                               
BTYPE   = 'intensity'  /                                                        
```
So I am puzzled. Both mask files were produced with SoFiA.

**Comment by paoloserra** [comment]
Yes it's a bit of a mess. But do we really need to get to the bottom if it?

When we create an empty mask we create it as int32. The imported masks are also made of integers -- no matter what astropy thinks. So why don't we just convert the imported masks to int32 as proposed above? That would solve this issue.

**Comment by vdhulst** [comment]
I agree, it is easier to allow (i.e. not worry about) various inputs and then treat them all the same (i.e. make them int32). Still annoying that we do not understand why astropy reacts so differently to input files that both have BITPIX = 16.

**Comment by SoFiA-Admin** [comment]
Could it be the BTYPE = 'intensity' keyword that triggers the conversion? This should not have been in the header to begin with, as the mask values are not intensity measurements.

**Comment by paoloserra** [comment]
In my case deleting BTYPE changes things but I'm not sure it resolves the problem. The dtype goes from 'float32' to '>f4', which i believe is also a float.

```
>>> from astropy.io import fits
>>> f=fits.open('SWmosaic.dkb12.15.16.line.felo.imap.pb_mask.fits')
>>> f[0].data.dtype
dtype('float32')
>>> head=f[0].header
>>> del(head['btype'])
>>> fits.writeto('testastropy.fits',f[0].data,head,overwrite=True)
>>> f.close()
>>> f=fits.open('testastropy.fits')
>>> f[0].data.dtype
dtype('>f4')
>>> f.close()
```

However, one can ignore all B* keywords with `do_not_scale_image_data` and the original data type is preserved:

>>> from astropy.io import fits
>>> f=fits.open('SWmosaic.dkb12.15.16.line.felo.imap.pb_mask.fits', do_not_scale_image_data=True)
>>> f[0].data.dtype
dtype('>i2')

Maybe this is the best solution? I guess we don't expect masks that make use of BSCALE and BZERO?

**Comment by RussellJurek** [comment]
This sounds like a robust solution to me. Just in case something inside
astropy changes in the future.

**Comment by vdhulst** [comment]
yes, this is probably the best thing to do. One comment is that WHISP masks are not binary masks like SoFiA produces. They are masked versions of the real data, so blanks outside the masks and the original data within the masks. But the 'mask' functionality is, I think, preserved with the proposed solution.
