### ISSUE TITLE
numpy.linalg.linalg.LinAlgError: 3-th leading minor of the array is not positive definite

### ISSUE THREAD

**Issue by 3rico** [SoFiA-Admin/SoFiA#181]
# On running SoFiA.session with the following parameters:

CNHI.maxScale	=	-1
CNHI.medianTest	=	true
CNHI.minScale	=	5
CNHI.pReq	=	1e-5
CNHI.qReq	=	3.8
CNHI.verbose	=	1
SCfind.edgeMode	=	constant
SCfind.kernelUnit	=	pixel
SCfind.kernels	=	[[ 0, 0, 0,'b'],[ 0, 0, 3,'b'],[ 0, 0, 7,'b'],[ 0, 0, 15,'b'],[ 3, 3, 0,'b'],[ 3, 3, 3,'b'],[ 3, 3, 7,'b'],[ 3, 3, 15,'b'],[ 6, 6, 0,'b'],[ 6, 6, 3,'b'],[ 6, 6, 7,'b'],[ 6, 6, 15,'b']]
SCfind.maskScaleXY	=	2.0
SCfind.maskScaleZ	=	2.0
SCfind.rmsMode	=	mad
SCfind.sizeFilter	=	0.0
SCfind.threshold	=	6.0
SCfind.verbose	=	true
flag.regions	=	[[0,'',0,'',0,68],[0,'',0,'',86,'']]
import.inFile	=	/home/maina/caratekit_brenda/PKS_2020-370/PKS_2020-370_20MHz/output/cubes/cube_2/PKS2020_J2023_3655_HI.image.fits
import.maskFile	=	
import.subcube	=	[]
import.subcubeMode	=	pixel
import.weightsFile	=	
import.weightsFunction	=	
merge.minSizeX	=	4
merge.minSizeY	=	4
merge.minSizeZ	=	2
merge.positivity	=	false
merge.radiusX	=	1
merge.radiusY	=	1
merge.radiusZ	=	1
optical.sourceCatalogue	=	
optical.spatSize	=	0.01
optical.specSize	=	1e+5
optical.storeMultiCat	=	false
parameters.dilateChan	=	1
parameters.dilateMask	=	false
parameters.dilatePixMax	=	10
parameters.dilateThreshold	=	0.02
parameters.fitBusyFunction	=	false
parameters.getUncertainties	=	false
parameters.optimiseMask	=	false
reliability.autoKernel	=	true
reliability.fMin	=	10.0
reliability.kernel	=	[0.15,0.05,0.1]
reliability.logPars	=	[1,1,1]
reliability.makePlot	=	false
reliability.negPerBin	=	1.0
reliability.parSpace	=	['n_pix','snr_sum','snr_max']
reliability.scaleKernel	=	0.55
reliability.skellamTol	=	-0.5
reliability.threshold	=	0.70
reliability.usecov	=	true
scaleNoise.edgeX	=	0
scaleNoise.edgeY	=	0
scaleNoise.edgeZ	=	0
scaleNoise.scaleX	=	false
scaleNoise.scaleY	=	false
scaleNoise.scaleZ	=	true
scaleNoise.statistic	=	mad
smooth.edgeMode	=	constant
smooth.kernel	=	gaussian
smooth.kernelX	=	3.0
smooth.kernelY	=	3.0
smooth.kernelZ	=	3.0
steps.doCNHI	=	false
steps.doCubelets	=	true
steps.doDebug	=	false
steps.doFlag	=	false
steps.doMerge	=	true
steps.doMom0	=	true
steps.doMom1	=	true
steps.doOptical	=	false
steps.doParameterise	=	true
steps.doReliability	=	true
steps.doSCfind	=	true
steps.doScaleNoise	=	false
steps.doSmooth	=	false
steps.doSubcube	=	false
steps.doThreshold	=	false
steps.doWavelet	=	false
steps.doWriteCat	=	true
steps.doWriteFilteredCube	=	false
steps.doWriteMask	=	true
threshold.clipMethod	=	relative
threshold.rmsMode	=	mad
threshold.threshold	=	4.0
threshold.verbose	=	false
wavelet.iterations	=	3
wavelet.positivity	=	false
wavelet.scaleXY	=	-1
wavelet.scaleZ	=	-1
wavelet.threshold	=	4.0
writeCat.basename	=	sofia_
writeCat.compress	=	false
writeCat.outputDir	=	/home/maina/caratekit_brenda/PKS_2020-370/PKS_2020-370_20MHz/output/cubes/cube_2/sofiia_output
writeCat.overwrite	=	true
writeCat.parameters	=	['*']
writeCat.writeASCII	=	true
writeCat.writeSQL	=	true
writeCat.writeXML	=	true

# I get the following error:

--- 4441.688 seconds since start
    Filter 6 6 7 b ...
    Estimating rms on subcube (x,y,z zoom = 1,1,1) ...
    Estimating rms on subcube sampling every 21 voxels ...
    ... Subcube shape is (37, 172, 172) ...
    ... mad rms = 1.41e-04 (data units)

--- 5086.954 seconds since start
    Filter 6 6 15 b ...
    Estimating rms on subcube (x,y,z zoom = 1,1,1) ...
    Estimating rms on subcube sampling every 21 voxels ...
    ... Subcube shape is (37, 172, 172) ...
    ... mad rms = 9.40e-05 (data units)
Source finding complete.
17144 of 9901440000 pixels detected (0.000173146532222%)

--- 5817.539 seconds since start
--- SoFiA: Merging detections
0 | |:| | : | |:| | 100% complete
********************* done.
Generating/updating sparse representations of sources . . .
0 | |:| | : | |:| | 100% complete
********************* done.
0 | |:| | : | |:| | 100% complete
********************* done.
Merging complete
60 sources detected: 57 positive, 3 negative.

--- 6026.528 seconds since start
--- SoFiA: Measuring cube noise to divide flux parameters by global rms
    Estimating rms on subcube (x,y,z zoom = 1,1,1) ...
    Estimating rms on subcube sampling every 21 voxels ...
    ... Subcube shape is (37, 172, 172) ...
    ... adjusting bin size to get a fraction of voxels in central bin >= 0.05
    ... negative rms = 6.86e-04 (data units)

--- 6048.308 seconds since start

--- 6048.308 seconds since start
--- SoFiA: Determining reliability
#Working in parameter space [ n_pix snr_sum snr_max ]
#Using a kernel with the shape of the covariance and size scaled by a factor 0.55.
#The sqrt(kernel) size is:
[[ 0.09568945  0.10767625  0.06905493]
 [ 0.10767625  0.12439584  0.07518166]
 [ 0.06905493  0.07518166  0.0516821 ]]
/home/brenda/SoFiA-1.1.0/build/lib.linux-x86_64-2.7/sofia/addrel.py:18: RuntimeWarning: invalid value encountered in sqrt
  self._norm_factor = np.sqrt(np.linalg.det(2*np.pi*self.covariance)) * self.n
Traceback (most recent call last):
  File "/home/brenda/SoFiA-1.1.0/sofia_pipeline.py", line 389, in <module>
    objects, reliable = addrel.EstimateRel(np.array(objects), outroot, catParNames, **Parameters['reliability'])
  File "/home/brenda/SoFiA-1.1.0/build/lib.linux-x86_64-2.7/sofia/addrel.py", line 189, in EstimateRel
    Nps = Np(pars[:,pos]) * Npos
  File "/usr/local/lib/python2.7/dist-packages/scipy/stats/kde.py", line 245, in evaluate
    whitening = linalg.cholesky(self.inv_cov)
  File "/usr/local/lib/python2.7/dist-packages/scipy/linalg/decomp_cholesky.py", line 91, in cholesky
    check_finite=check_finite)
  File "/usr/local/lib/python2.7/dist-packages/scipy/linalg/decomp_cholesky.py", line 40, in _cholesky
    "definite" % info)
numpy.linalg.linalg.LinAlgError: 3-th leading minor of the array is not positive definite
`

# Any ideas as to what's causing this?

**Comment by paoloserra** [comment]
Can you please add the start of the log such that we can see your python, numpy, astropy versions?

It looks like you're still running python2.7.

**Comment by RussellJurek** [comment]
Hi everyone,
            from the message it looks like the cholesky decomposition in Numpy is falling over because of a singular matrix. 

The Numpy, etc. versions will be very helpful here. 

Cheers,
Russell
